defaults:
  - experiment: random_30pct
  - train: default
  - data: same
  - tracking: wandb
  - model: cnn
  - _self_


base_path: "/workspaces/federated-learning-dropout"
device: ${train.device}
run_name: ${experiment.name}_${experiment.pattern_train}_${experiment.dropout_rate_training}_${experiment.pattern_eval}_${experiment.dropout_rate_eval}
seed: 42
num_clients: 4
num_rounds: 3
gpus : 0

# Hydra configuration
hydra:
  run:
    dir: outputs/${run_name}
  sweep:
    dir: multirun
    subdir: ${run_name}